version: '3'
services:
    redis:
        container_name: redis
        image: redis:4.0.6-alpine
        ports:
          - "6379:6379"
        volumes:
            - redis:/redis

    dvla-app:
        image: dvla-app
        container_name: dvla-app
        build: ./
        restart: always
        ports:
            - '5000'
        volumes:
            - grabs:/home/myuser/data/grabs
        depends_on:
            - redis
    
    webhook-tester:
        image: platerecognizer/webhook-tester
        container_name: webhook-tester
        environment:
        - URL=http://dvla-app:5000/plate_detected
    
    worker:
        build: .
        command: rq worker --url redis://redis:6379/0 default
        depends_on:
        - redis

volumes:
  grabs:
  redis: