version: '3'
services:
    # redis:
    #     container_name: redis
    #     image: redis:4.0.6-alpine
    #     ports:
    #       - "6379:6379"
    #     volumes:
    #         - ./redis:/redis

    dvla-app:
        image: dvla-app
        container_name: dvla-app
        build: ./
        restart: always
        ports:
            - '5000'
        volumes:
            - grabs:/home/myuser/data/grabs
    
    webhook-tester:
        image: platerecognizer/webhook-tester
        container_name: webhook-tester
        environment:
        - URL=http://dvla-app:5000/send

volumes:
  grabs:
